-- Artistry set parallels: numbered rainbow, base autographs, and rookie patch autos.
-- New enum values only; CardTemplates for these are created by seed / backfill-templates.
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RED';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_BLUE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_GREEN';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_BLUE_ICE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RAINBOW';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_PURPLE_ICE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_GOLD';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_WHITE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_BLACK';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RED_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_BLUE_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_GREEN_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_BLUE_ICE_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RAINBOW_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_PURPLE_ICE_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_GOLD_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_WHITE_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_BLACK_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RPA_50';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RPA_35';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RPA_25';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RPA_10';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RPA_3';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'ART_RPA_1';
