-- Reliquary set: its own four-tier checklist (base / patch / auto / RPA rainbows).
-- New enum values only; CardTemplates for these are created by seed / import.
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RC';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_GREEN';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_ORANGE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RED';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_OFL';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_WHITE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PINK';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_GOLD';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_GOLD_SHIMMER';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_GREEN_SHIMMER';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_BLACK';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_RC';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_GREEN';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_ORANGE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_RED';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_OFL';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_WHITE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_PINK';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_GOLD';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_GOLD_SHIMMER';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_GREEN_SHIMMER';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_PATCH_BLACK';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_AUTO';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_AUTO_ORANGE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_AUTO_RED';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_AUTO_OFL';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_AUTO_GOLD';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_AUTO_GREEN_SHIMMER';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_AUTO_BLACK';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RPA';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RPA_OFL';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RPA_WHITE';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RPA_RED';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RPA_GOLD';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RPA_GOLD_SHIMMER';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RPA_GREEN_SHIMMER';
ALTER TYPE "Parallel" ADD VALUE IF NOT EXISTS 'RLQ_RPA_BLACK';

-- Limited print run for boxes: cap supply and track how many have been opened.
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "totalBoxes" INTEGER;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "boxesOpened" INTEGER NOT NULL DEFAULT 0;
